server:
  port: 8085

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:h2:mem:paymentdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce-platform

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true

  tracing:
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
  file:
    name: logs/payment-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} service=${spring.application.name} traceId=%X{traceId:-} spanId=%X{spanId:-} orderId=%X{orderId:-} orderCode=%X{orderCode:-} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} service=${spring.application.name} traceId=%X{traceId:-} spanId=%X{spanId:-} orderId=%X{orderId:-} orderCode=%X{orderCode:-} - %msg%n"