server:
  port: 8082

payment-service:
  url: http://localhost:8085

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5433/orderdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce-platform

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 3000
          payment-service:
            micrometer:
              enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true

  tracing:
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

resilience4j:
  retry:
    instances:
      paymentRetry:
        max-attempts: 4
        wait-duration: 500ms
        retry-exceptions:
          - com.ecommerce.orderservice.exception.RetryablePaymentException
        ignore-exceptions:
          - com.ecommerce.orderservice.exception.NonRetryablePaymentException

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    io.github.resilience4j.retry: DEBUG
  file:
    name: logs/order-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} service=${spring.application.name} traceId=%X{traceId:-} spanId=%X{spanId:-} orderId=%X{orderId:-} orderCode=%X{orderCode:-} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} service=${spring.application.name} traceId=%X{traceId:-} spanId=%X{spanId:-} orderId=%X{orderId:-} orderCode=%X{orderCode:-} - %msg%n"